apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: IMAGE_PLACEHOLDER_BACKEND
    newName: swr.cn-north-4.myhuaweicloud.com/jintianchisha/backend
    newTag: latest
  - name: IMAGE_PLACEHOLDER_FRONTEND
    newName: swr.cn-north-4.myhuaweicloud.com/jintianchisha/frontend
    newTag: latest
